/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UratemeRouteImport } from './routes/urateme'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QmasterRouteImport } from './routes/qmaster'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IntegrahrisGovernmentRouteImport } from './routes/integrahris-government'
import { Route as Integrahris365RouteImport } from './routes/integrahris-365'
import { Route as IntegraRouteImport } from './routes/integra'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as GpmsRouteImport } from './routes/gpms'
import { Route as DocutrakrRouteImport } from './routes/docutrakr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'

const UratemeRoute = UratemeRouteImport.update({
  id: '/urateme',
  path: '/urateme',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QmasterRoute = QmasterRouteImport.update({
  id: '/qmaster',
  path: '/qmaster',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrahrisGovernmentRoute = IntegrahrisGovernmentRouteImport.update({
  id: '/integrahris-government',
  path: '/integrahris-government',
  getParentRoute: () => rootRouteImport,
} as any)
const Integrahris365Route = Integrahris365RouteImport.update({
  id: '/integrahris-365',
  path: '/integrahris-365',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegraRoute = IntegraRouteImport.update({
  id: '/integra',
  path: '/integra',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const GpmsRoute = GpmsRouteImport.update({
  id: '/gpms',
  path: '/gpms',
  getParentRoute: () => rootRouteImport,
} as any)
const DocutrakrRoute = DocutrakrRouteImport.update({
  id: '/docutrakr',
  path: '/docutrakr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docutrakr': typeof DocutrakrRoute
  '/gpms': typeof GpmsRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integra': typeof IntegraRoute
  '/integrahris-365': typeof Integrahris365Route
  '/integrahris-government': typeof IntegrahrisGovernmentRoute
  '/projects': typeof ProjectsRoute
  '/qmaster': typeof QmasterRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/urateme': typeof UratemeRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docutrakr': typeof DocutrakrRoute
  '/gpms': typeof GpmsRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integra': typeof IntegraRoute
  '/integrahris-365': typeof Integrahris365Route
  '/integrahris-government': typeof IntegrahrisGovernmentRoute
  '/projects': typeof ProjectsRoute
  '/qmaster': typeof QmasterRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/urateme': typeof UratemeRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docutrakr': typeof DocutrakrRoute
  '/gpms': typeof GpmsRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integra': typeof IntegraRoute
  '/integrahris-365': typeof Integrahris365Route
  '/integrahris-government': typeof IntegrahrisGovernmentRoute
  '/projects': typeof ProjectsRoute
  '/qmaster': typeof QmasterRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/urateme': typeof UratemeRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/docutrakr'
    | '/gpms'
    | '/helpdesk'
    | '/integra'
    | '/integrahris-365'
    | '/integrahris-government'
    | '/projects'
    | '/qmaster'
    | '/services'
    | '/solutions'
    | '/urateme'
    | '/solutions/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/docutrakr'
    | '/gpms'
    | '/helpdesk'
    | '/integra'
    | '/integrahris-365'
    | '/integrahris-government'
    | '/projects'
    | '/qmaster'
    | '/services'
    | '/solutions'
    | '/urateme'
    | '/solutions/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/docutrakr'
    | '/gpms'
    | '/helpdesk'
    | '/integra'
    | '/integrahris-365'
    | '/integrahris-government'
    | '/projects'
    | '/qmaster'
    | '/services'
    | '/solutions'
    | '/urateme'
    | '/solutions/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DocutrakrRoute: typeof DocutrakrRoute
  GpmsRoute: typeof GpmsRoute
  HelpdeskRoute: typeof HelpdeskRoute
  IntegraRoute: typeof IntegraRoute
  Integrahris365Route: typeof Integrahris365Route
  IntegrahrisGovernmentRoute: typeof IntegrahrisGovernmentRoute
  ProjectsRoute: typeof ProjectsRoute
  QmasterRoute: typeof QmasterRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  UratemeRoute: typeof UratemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urateme': {
      id: '/urateme'
      path: '/urateme'
      fullPath: '/urateme'
      preLoaderRoute: typeof UratemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qmaster': {
      id: '/qmaster'
      path: '/qmaster'
      fullPath: '/qmaster'
      preLoaderRoute: typeof QmasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrahris-government': {
      id: '/integrahris-government'
      path: '/integrahris-government'
      fullPath: '/integrahris-government'
      preLoaderRoute: typeof IntegrahrisGovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrahris-365': {
      id: '/integrahris-365'
      path: '/integrahris-365'
      fullPath: '/integrahris-365'
      preLoaderRoute: typeof Integrahris365RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integra': {
      id: '/integra'
      path: '/integra'
      fullPath: '/integra'
      preLoaderRoute: typeof IntegraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpms': {
      id: '/gpms'
      path: '/gpms'
      fullPath: '/gpms'
      preLoaderRoute: typeof GpmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docutrakr': {
      id: '/docutrakr'
      path: '/docutrakr'
      fullPath: '/docutrakr'
      preLoaderRoute: typeof DocutrakrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DocutrakrRoute: DocutrakrRoute,
  GpmsRoute: GpmsRoute,
  HelpdeskRoute: HelpdeskRoute,
  IntegraRoute: IntegraRoute,
  Integrahris365Route: Integrahris365Route,
  IntegrahrisGovernmentRoute: IntegrahrisGovernmentRoute,
  ProjectsRoute: ProjectsRoute,
  QmasterRoute: QmasterRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  UratemeRoute: UratemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
