/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UratemeRouteImport } from './routes/urateme'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QmasterRouteImport } from './routes/qmaster'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IntegrahrisGovernmentRouteImport } from './routes/integrahris-government'
import { Route as Integrahris365RouteImport } from './routes/integrahris-365'
import { Route as IntegraRouteImport } from './routes/integra'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as GpmsRouteImport } from './routes/gpms'
import { Route as DocutrakrRouteImport } from './routes/docutrakr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as CareersQaTesterAutomationRouteImport } from './routes/careers.qa-tester-automation'
import { Route as CareersItTraineeRouteImport } from './routes/careers.it-trainee'
import { Route as CareersBackendDeveloperRouteImport } from './routes/careers.backend-developer'
import { Route as CareersAccountManagementTraineeRouteImport } from './routes/careers.account-management-trainee'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UratemeRoute = UratemeRouteImport.update({
  id: '/urateme',
  path: '/urateme',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QmasterRoute = QmasterRouteImport.update({
  id: '/qmaster',
  path: '/qmaster',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrahrisGovernmentRoute = IntegrahrisGovernmentRouteImport.update({
  id: '/integrahris-government',
  path: '/integrahris-government',
  getParentRoute: () => rootRouteImport,
} as any)
const Integrahris365Route = Integrahris365RouteImport.update({
  id: '/integrahris-365',
  path: '/integrahris-365',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegraRoute = IntegraRouteImport.update({
  id: '/integra',
  path: '/integra',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const GpmsRoute = GpmsRouteImport.update({
  id: '/gpms',
  path: '/gpms',
  getParentRoute: () => rootRouteImport,
} as any)
const DocutrakrRoute = DocutrakrRouteImport.update({
  id: '/docutrakr',
  path: '/docutrakr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SolutionsRoute,
} as any)
const CareersQaTesterAutomationRoute =
  CareersQaTesterAutomationRouteImport.update({
    id: '/qa-tester-automation',
    path: '/qa-tester-automation',
    getParentRoute: () => CareersRoute,
  } as any)
const CareersItTraineeRoute = CareersItTraineeRouteImport.update({
  id: '/it-trainee',
  path: '/it-trainee',
  getParentRoute: () => CareersRoute,
} as any)
const CareersBackendDeveloperRoute = CareersBackendDeveloperRouteImport.update({
  id: '/backend-developer',
  path: '/backend-developer',
  getParentRoute: () => CareersRoute,
} as any)
const CareersAccountManagementTraineeRoute =
  CareersAccountManagementTraineeRouteImport.update({
    id: '/account-management-trainee',
    path: '/account-management-trainee',
    getParentRoute: () => CareersRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/docutrakr': typeof DocutrakrRoute
  '/gpms': typeof GpmsRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integra': typeof IntegraRoute
  '/integrahris-365': typeof Integrahris365Route
  '/integrahris-government': typeof IntegrahrisGovernmentRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/qmaster': typeof QmasterRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/urateme': typeof UratemeRoute
  '/careers/account-management-trainee': typeof CareersAccountManagementTraineeRoute
  '/careers/backend-developer': typeof CareersBackendDeveloperRoute
  '/careers/it-trainee': typeof CareersItTraineeRoute
  '/careers/qa-tester-automation': typeof CareersQaTesterAutomationRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/docutrakr': typeof DocutrakrRoute
  '/gpms': typeof GpmsRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integra': typeof IntegraRoute
  '/integrahris-365': typeof Integrahris365Route
  '/integrahris-government': typeof IntegrahrisGovernmentRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/qmaster': typeof QmasterRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/urateme': typeof UratemeRoute
  '/careers/account-management-trainee': typeof CareersAccountManagementTraineeRoute
  '/careers/backend-developer': typeof CareersBackendDeveloperRoute
  '/careers/it-trainee': typeof CareersItTraineeRoute
  '/careers/qa-tester-automation': typeof CareersQaTesterAutomationRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/docutrakr': typeof DocutrakrRoute
  '/gpms': typeof GpmsRoute
  '/helpdesk': typeof HelpdeskRoute
  '/integra': typeof IntegraRoute
  '/integrahris-365': typeof Integrahris365Route
  '/integrahris-government': typeof IntegrahrisGovernmentRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/qmaster': typeof QmasterRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/urateme': typeof UratemeRoute
  '/careers/account-management-trainee': typeof CareersAccountManagementTraineeRoute
  '/careers/backend-developer': typeof CareersBackendDeveloperRoute
  '/careers/it-trainee': typeof CareersItTraineeRoute
  '/careers/qa-tester-automation': typeof CareersQaTesterAutomationRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/docutrakr'
    | '/gpms'
    | '/helpdesk'
    | '/integra'
    | '/integrahris-365'
    | '/integrahris-government'
    | '/privacy'
    | '/projects'
    | '/qmaster'
    | '/services'
    | '/solutions'
    | '/urateme'
    | '/careers/account-management-trainee'
    | '/careers/backend-developer'
    | '/careers/it-trainee'
    | '/careers/qa-tester-automation'
    | '/solutions/$slug'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/docutrakr'
    | '/gpms'
    | '/helpdesk'
    | '/integra'
    | '/integrahris-365'
    | '/integrahris-government'
    | '/privacy'
    | '/projects'
    | '/qmaster'
    | '/services'
    | '/solutions'
    | '/urateme'
    | '/careers/account-management-trainee'
    | '/careers/backend-developer'
    | '/careers/it-trainee'
    | '/careers/qa-tester-automation'
    | '/solutions/$slug'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/docutrakr'
    | '/gpms'
    | '/helpdesk'
    | '/integra'
    | '/integrahris-365'
    | '/integrahris-government'
    | '/privacy'
    | '/projects'
    | '/qmaster'
    | '/services'
    | '/solutions'
    | '/urateme'
    | '/careers/account-management-trainee'
    | '/careers/backend-developer'
    | '/careers/it-trainee'
    | '/careers/qa-tester-automation'
    | '/solutions/$slug'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  DocutrakrRoute: typeof DocutrakrRoute
  GpmsRoute: typeof GpmsRoute
  HelpdeskRoute: typeof HelpdeskRoute
  IntegraRoute: typeof IntegraRoute
  Integrahris365Route: typeof Integrahris365Route
  IntegrahrisGovernmentRoute: typeof IntegrahrisGovernmentRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  QmasterRoute: typeof QmasterRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  UratemeRoute: typeof UratemeRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urateme': {
      id: '/urateme'
      path: '/urateme'
      fullPath: '/urateme'
      preLoaderRoute: typeof UratemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qmaster': {
      id: '/qmaster'
      path: '/qmaster'
      fullPath: '/qmaster'
      preLoaderRoute: typeof QmasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrahris-government': {
      id: '/integrahris-government'
      path: '/integrahris-government'
      fullPath: '/integrahris-government'
      preLoaderRoute: typeof IntegrahrisGovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrahris-365': {
      id: '/integrahris-365'
      path: '/integrahris-365'
      fullPath: '/integrahris-365'
      preLoaderRoute: typeof Integrahris365RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integra': {
      id: '/integra'
      path: '/integra'
      fullPath: '/integra'
      preLoaderRoute: typeof IntegraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpms': {
      id: '/gpms'
      path: '/gpms'
      fullPath: '/gpms'
      preLoaderRoute: typeof GpmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docutrakr': {
      id: '/docutrakr'
      path: '/docutrakr'
      fullPath: '/docutrakr'
      preLoaderRoute: typeof DocutrakrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/careers/qa-tester-automation': {
      id: '/careers/qa-tester-automation'
      path: '/qa-tester-automation'
      fullPath: '/careers/qa-tester-automation'
      preLoaderRoute: typeof CareersQaTesterAutomationRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/it-trainee': {
      id: '/careers/it-trainee'
      path: '/it-trainee'
      fullPath: '/careers/it-trainee'
      preLoaderRoute: typeof CareersItTraineeRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/backend-developer': {
      id: '/careers/backend-developer'
      path: '/backend-developer'
      fullPath: '/careers/backend-developer'
      preLoaderRoute: typeof CareersBackendDeveloperRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/account-management-trainee': {
      id: '/careers/account-management-trainee'
      path: '/account-management-trainee'
      fullPath: '/careers/account-management-trainee'
      preLoaderRoute: typeof CareersAccountManagementTraineeRouteImport
      parentRoute: typeof CareersRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CareersRouteChildren {
  CareersAccountManagementTraineeRoute: typeof CareersAccountManagementTraineeRoute
  CareersBackendDeveloperRoute: typeof CareersBackendDeveloperRoute
  CareersItTraineeRoute: typeof CareersItTraineeRoute
  CareersQaTesterAutomationRoute: typeof CareersQaTesterAutomationRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersAccountManagementTraineeRoute: CareersAccountManagementTraineeRoute,
  CareersBackendDeveloperRoute: CareersBackendDeveloperRoute,
  CareersItTraineeRoute: CareersItTraineeRoute,
  CareersQaTesterAutomationRoute: CareersQaTesterAutomationRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface SolutionsRouteChildren {
  SolutionsSlugRoute: typeof SolutionsSlugRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsSlugRoute: SolutionsSlugRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  DocutrakrRoute: DocutrakrRoute,
  GpmsRoute: GpmsRoute,
  HelpdeskRoute: HelpdeskRoute,
  IntegraRoute: IntegraRoute,
  Integrahris365Route: Integrahris365Route,
  IntegrahrisGovernmentRoute: IntegrahrisGovernmentRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  QmasterRoute: QmasterRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  UratemeRoute: UratemeRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
